- name: for
  identifier: for
  output: FOR
- name: if
  identifier: if
  output: IF
- name: LB
  identifier: (
  output: LB
- name: RB
  identifier: )
  output: RB
- name: LK
  identifier: "{"
  output: LK
- name: RK
  identifier: "}"
  output: RK
- name: "="
  identifier: "="
  output: EQ
- name: "=="
  identifier: "=="
  output: EQCMP
- name: "+"
  identifier: "+"
  output: PLUS
- name: "-"
  identifier: "-"
  output: MINUS
- name: int
  identifier: int
  output: INT