for:
  output: <FOR>
if:
  output: <IF>
while:
  output: <WHILE>
readln:
  output: <READLN>
break:
  output: <BREAK>
return:
  output: <RETURN>
"true":
  output: <TRUE>
"false":
  output: <FALSE>
",":
  output: <COMMA>
"[":
  output: <OPEN_BRACKETS>
"]":
  output: <CLOSE_BRACKETS>
"(":
  output: <OPEN_PARENTHESES>
")":
  output: <CLOSE_PARENTHESES>
"{":
  output: <OPEN_BRACES>
"}":
  output: <CLOSE_BRACES>
"+":
  output: <PLUS>
"-":
  output: <MINUS>
int:
  output: <INT>
"--":
  output: <DECREMENT>
"++":
  output: <INCREMENT>
"!":
  output: <NEG>
"=":
  output: <ASSIGN>
"==":
  output: <EQUALS>
"<":
  output: <LESS_THAN> # Less Than (menor que)
"<=":
  output: <LESS_THAN_EQUAL> # Less than or Equal (menor ou igual que)
">":
  output: <GREATER_THAN> # Greater Than (maior que)
">=":
  output: <GREATER_THAN_EQUAL> # Greater than or Equal (maior ou igual que)
"!=":
  output: <DIFF>
"||":
  output: <OR>
"&&":
  output: <AND>
"*":
  output: <MULT>
"/":
  output: <DIV>
"%":
  output: <MOD>
";":
  output: <SEMICOLON>