for:
  output: FOR
if:
  output: IF
(:
  output: LB
):
  output: RB
"{":
  output: LK
"}":
  output: RK
"=":
  output: EQ
"==":
  output: EQCMP
"+":
  output: PLUS
"-":
  output: MINUS
int:
  output: INT