- name: for
  identifier: for
  output: FOR
- name: if
  identifier: if
  output: IF
- name: LB
  identifier: (
  output: LB
- name: RB
  identifier: )
  output: RB
- name: "="
  identifier: "="
  output: EQ
- name: "+"
  identifier: "+"
  output: PLUS
- name: "-"
  identifier: "-"
  output: MINUS
- name: int
  identifier: int
  output: INT